language: node_js

node_js:
    - "12"

sudo: false

git:
    submodules: false

services: mongodb

before_script:
    - npm install

script:
    - npm start
    - npm run test

after_success:
    - npm run report-coveralls
    - npm run report-codecov